### ISSUE TITLE
hasValue returns false when model is 0

### ISSUE THREAD

**Issue by fbraem** [wearebraid/vue-formulate#138]
**Describe the bug**
When using a slider and the form model is initialized to 0, the value isn't shown. I think this is because hasValue returns false. It works when the value is set to '0', but then the model type becomes a string.

**To Reproduce**
Create a form with a range and attach a model with value 0.

**Reproduction**
https://codepen.io/fbraem/pen/xxZLQEG

**Expected behavior**
Model should be set to 0 and hasValue should return true. I don't know if this is a breaking change for other input values.

**Device information:**
- Version 2.4.1

**Comment by justin-schroeder** [comment]
Been thinking about this one over the weekend some. You're 100% correct, `hasValue` should definitely return true for a value of `Number 0` or `String "0"`. I think the rest of the behavior is working as expected right? I'll mark it as a bug.

**Comment by justin-schroeder** [comment]
@fbraem Thanks for pointing this out. It should be fixed now in `v2.4.2` 👍

**Comment by fbraem** [comment]
@justin-schroeder I still think there is a problem. I've updated the example to use 2.4.2 and the first range slider still doesn't show a value.

https://codepen.io/fbraem/pen/xxZLQEG

**Comment by justin-schroeder** [comment]
Ahh. I misunderstood the original issue post. The hasValue part was fixed in 2.4.2, but your post was specific to the show-value prop and I missed that part. I’ll reopen this!

**Comment by fbraem** [comment]
It seems that context.model isn't set. And that made me think about hasValue. To be precise, I'm creating a custom range:

````
<template>
  <!-- Based on https://codepen.io/seanstopnik/pen/CeLqA -->
  <div
    :class="`formulate-input-element formulate-input-element--${context.type}`"
    :data-type="context.type">
    <div class="w-full">
      <input
        type="range"
        v-model="context.model"
        class="appearance-none range-slider__range"
        v-bind="context.attributes"
      />
      <div
        class="range-slider__value"
      >
        {{ context.model }}
      </div>
    </div>
  </div>
</template>
````

When the associated model is set to non-zero, the value is shown. When the value is zero, context.model isn't set.

**Comment by justin-schroeder** [comment]
This is fixed and published in `v2.4.3`
